### ISSUE TITLE
Crash for each voice in the menu

### ISSUE THREAD

**Issue by ziobbe** [M-griffin/EtherTerm#77]
I can't seem to be able to use any of the menu functions except exit.
I built it using the build.sh in the build directory
for example this is the error that crashes it if i choose Add to the list
`/build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:1058: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference = char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.
`

**Comment by M-griffin** [comment]
Hi @ziobbe, 

Thank you for taking a look and showing some interest.  
I'll need a little more information so that I can try to re-produce the issues and help you.

Can you tell me what Operating System and Distribution you are running? 
For Example `Linux Ubuntu` and `Ubuntu 22.04 LTS` for the version.

**Comment by M-griffin** [comment]
My brain is a little foggy since I haven't built the program or ran it for sometime in Linux.  I just pulled it down into my latest Linux Mint install and tested it.  I don't see the errors when I click on change the light bars..  and hit <ENTER> on Add etc..  However, only the CONNECT and EXIT are wired up at this time.. The other options are not yet coded..  I almost forgot.

If you want to add a new system to call, you have to edit the Dialing Directory YAML file
`build/assets/dialing_directory.yaml`

If you edit the file you'll see a single entry.. I though there were more but I must have cleaned them  up in the past or when I converted from XML to YAML.

```
system_entry:
  index: 0
  name: Haunting The Chapel
  ip: htc.zapto.org
  port: 23
  protocol: Telnet
  login: ""
  password: ""
  font: vga8x16.bmp
  key_map: VT100
  term_type: ANSI
  term_size: 80x25
  use_pipe_colors: true
```

1. So take this block, and copy/paste it
2. Increment the index `index: 0` to `index: 1` add 1 for each new entry.
3. Update the Name, IP, and Port for the new entry, then restart the program and the new system should be added.  

Sorry for the inconvenience, I've been meaning to finish that and it's slip past me. 

Here are a few examples to add and cool systems to try:
```
system_entry:
  index: 1
  name: xibalba.l33t.codes
  ip: xibalba.l33t.codes
  port: 44510
  protocol: Telnet
  login: ""
  password: ""
  font: vga8x16.bmp
  key_map: ANSI
  term_type: ANSI
  term_size: 80x25
  use_pipe_colors: True
system_entry:
  index: 2
  name: hysteriabbs.com
  ip: hysteriabbs.com
  port: 23
  protocol: Telnet
  login: ""
  password: ""
  font: vga8x16.bmp
  key_map: ANSI
  term_type: ANSI
  term_size: 80x25
  use_pipe_colors: True
system_entry:
  index: 3
  name: 79 Columns
  ip: oddnetwork.org
  port: 23
  protocol: TELNET
  login: ""
  password: ""
  font: vga8x16.bmp
  key_map: VT100
  term_type: ANSI
  term_size: 80x25
  use_pipe_colors: False
system_entry:
  index: 4
  name: Black Flag (Mystic)
  ip: blackflag.acid.org
  port: 23
  protocol: TELNET
  login: ""
  password: ""
  font: vga8x16.bmp
  key_map: ANSI
  term_type: ANSI
  term_size: 80x25
  use_pipe_colors: False
system_entry:
  index: 5
  name: bbs.inktwo.com
  ip: bbs.inktwo.com
  port: 23
  protocol: TELNET
  login: ""
  password: ""
  font: vga8x16.bmp
  key_map: ANSI
  term_type: ANSI
  term_size: 80x25
  use_pipe_colors: False
```
